"""
VoxLens — Export Endpoint

Export meeting data as markdown.
"""

from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import PlainTextResponse
from sqlalchemy.orm import Session

from app.database import get_db
from app.models import Meeting, TranscriptChunk, SummaryReport
from app.schemas import ExportResponse

router = APIRouter()


def _format_time(seconds: float) -> str:
    """Format seconds into HH:MM:SS."""
    hours = int(seconds // 3600)
    minutes = int((seconds % 3600) // 60)
    secs = int(seconds % 60)
    if hours > 0:
        return f"{hours:02d}:{minutes:02d}:{secs:02d}"
    return f"{minutes:02d}:{secs:02d}"


@router.get(
    "/export/{meeting_id}",
    response_model=ExportResponse,
    tags=["Export"],
)
async def export_meeting(meeting_id: str, db: Session = Depends(get_db)):
    """Export meeting data as a markdown document."""
    meeting = db.query(Meeting).filter(Meeting.id == meeting_id).first()
    if not meeting:
        raise HTTPException(status_code=404, detail="Meeting not found")

    report = (
        db.query(SummaryReport)
        .filter(SummaryReport.meeting_id == meeting_id)
        .first()
    )
    chunks = (
        db.query(TranscriptChunk)
        .filter(TranscriptChunk.meeting_id == meeting_id)
        .order_by(TranscriptChunk.chunk_index)
        .all()
    )

    # Build markdown
    lines = []
    title = meeting.title or "Untitled Meeting"
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"**Source:** {meeting.source_url or meeting.file_name or 'N/A'}")
    lines.append(f"**Date:** {meeting.created_at.strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"**Language:** {meeting.language}")
    if meeting.duration_seconds:
        lines.append(f"**Duration:** {_format_time(meeting.duration_seconds)}")
    lines.append("")

    if report:
        if report.summary:
            lines.append("## Summary")
            lines.append("")
            lines.append(report.summary)
            lines.append("")

        if report.bullet_points:
            lines.append("## Key Points")
            lines.append("")
            for point in report.bullet_points:
                lines.append(f"- {point}")
            lines.append("")

        if report.key_takeaways:
            lines.append("## Key Takeaways")
            lines.append("")
            for takeaway in report.key_takeaways:
                lines.append(f"- {takeaway}")
            lines.append("")

        if report.action_items:
            lines.append("## Action Items")
            lines.append("")
            lines.append("| Task | Owner | Deadline |")
            lines.append("|------|-------|----------|")
            for item in report.action_items:
                task = item.get("task", "N/A")
                owner = item.get("owner", "Unknown")
                deadline = item.get("deadline", "Not specified")
                lines.append(f"| {task} | {owner} | {deadline} |")
            lines.append("")

        if report.decisions:
            lines.append("## Key Decisions")
            lines.append("")
            for decision in report.decisions:
                lines.append(f"- {decision}")
            lines.append("")

        if report.open_questions:
            lines.append("## Open Questions")
            lines.append("")
            for question in report.open_questions:
                lines.append(f"- {question}")
            lines.append("")

    if chunks:
        lines.append("## Transcript")
        lines.append("")
        for chunk in chunks:
            timestamp = _format_time(chunk.start_time)
            lines.append(f"**[{timestamp}]** {chunk.text}")
            lines.append("")

    lines.append("---")
    lines.append(f"*Generated by VoxLens — {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*")

    markdown = "\n".join(lines)
    safe_title = "".join(c if c.isalnum() or c in " -_" else "" for c in title)
    filename = f"{safe_title.strip().replace(' ', '_')}_report.md"

    return ExportResponse(
        meeting_id=meeting_id,
        markdown=markdown,
        filename=filename,
    )
